export const types = {
    NEW_TAB: 'NEW_TAB',
    NEW_TAB_DATA: 'NEW_TAB_DATA',
    SAVE_SORT_STATE: 'SAVE_SORT_STATE',
    SAVE_FILTER_STATE: 'SAVE_FILTER_STATE',
    RESTORE_STATE:'RESTORE_STATE'
};
